services:
    app:
        build: .
        container_name: laravel-app
        ports:
            - "8000:8000"
        environment:
            APP_NAME: Laravel
            APP_ENV: local
            APP_KEY: base64:mbOGc/UUqH9UtzKKB5quKMDJHLbu+6oICPe71M3yWlQ=
            APP_DEBUG: "true"
            APP_URL: http://localhost
            APP_TIMEZONE: UTC
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite
            LARAVEL_STORAGE_PATH: /var/www/html/storage
            SESSION_DRIVER: file
            SESSION_LIFETIME: 120
            SESSION_ENCRYPT: "false"
            SESSION_PATH: /
            LOG_CHANNEL: stack
            LOG_LEVEL: debug
